# Generated by Django 2.2.16 on 2022-05-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='random', max_length=256, verbose_name='Код подтверждения'),
        ),
    ]
