# Generated by Django 2.2.16 on 2022-05-16 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220516_2039'),
        ('users', '0003_auto_20220516_2102'),
    ]

    operations = [
    ]
