# Generated by Django 2.2.16 on 2022-05-17 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220516_2153'),
        ('users', '0004_merge_20220516_2136'),
    ]

    operations = [
    ]
