# Generated by Django 2.2.16 on 2022-05-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220513_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Код подтверждения'),
        ),
    ]
